# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#

# Configure user environment 
singleuser:
  image:
    # You should replace the "latest" tag with a fixed version from:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/HEAD/datascience-notebook/Dockerfile
    name: minimal-notebook
    tag: latest
  # `cmd: null` allows the custom CMD of the Jupyter docker-stacks to be used
  # which performs further customization on startup.
  cmd: null

prePuller:
  hook:
    enabled: false

# TODO: Install additional python dependencies
hub:
  config:
    # GitHubOAuthenticator:
    #   client_id: TODO
    #   client_secret: TODO
    #   oauth_callback_url: http://localhost:30000/hub/oauth_callback
    GitLabOAuthenticator:
      client_id: TODO
      client_secret: TODO
      oauth_callback_url: http://localhost:30000/hub/oauth_callback
      gitlab_url: https://gitlab.switch.ch # http://gitlab.epfl.ch
    JupyterHub:
      authenticator_class: gitlab #test
  image:
    name: k8s-hub 
    tag: latest
  loadRoles:
    user:
      scopes:
        - self
    downloadservice:
      users:
        - volodymyr.savchenko
        - andrii.neronov
        - pavlo.kashko
        - bastien.wermeille
      scopes:
        - "access:services!service=downloadservice"
  services:
    downloadservice:
      url: http://hub:5000
      command:
        - /usr/local/bin/python3
        - /downloadservice/downloadservice/cli.py
  networkPolicy:
    ingress:
      - ports:
          - port: 5000
        from:
          - podSelector:
              matchLabels:
                hub.jupyter.org/network-access-hub: "true"
  service:
    extraPorts:
      - port: 5000
        targetPort: 5000
        name: downloadservice
  # extraConfig:
  #   00-services-config: |
  #     c.JupyterHub.services = [
  #         {
  #             'name': 'downloadservice',
  #             'command': [sys.executable, '/downloadservice/downloadservice/cli.py']
  #         }
  #     ]
    # 00-services-config: |
    #   c.JupyterHub.services = [
    #       {
    #           'name': 'idle-culler',
    #           'command': [sys.executable, '-m', 'poetry', 'run', 'flask', '--app=/downloadservice/downloadservice/app', 'run']
    #       }
    #   ]
